name: Daily NREGA Scraper Run

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Recreate credentials.json from secret
      run: echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > credentials.json

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'   # or whatever Node version you use

    - name: Install dependencies
      run: npm install      # if you have a package.json, otherwise skip

    - name: Run scraper script
      run: node runall.js
